version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  backend:
    image: sprinter911/nestjs-app1:latest
    container_name: nestjs-backend
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis

volumes:
  redis-data:
