version: '3.8'

services:
  redis:
    image: "redis:latest"
    container_name: "backend-redis"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  nestjs-app:
    build:
      context: .
      dockerfile: ../Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      REDIS_HOST: backend-redis

volumes:
  redis-data:
